import { useEffect, useState } from 'react';
import { commands } from '../lib/tauri';
import type { ApprovalRequest, OperationPreview, OperationReceipt, RowvaError } from '../types/rowva';

const value=(v:unknown)=>v===null||v===undefined?'None':typeof v==='string'?v:JSON.stringify(v);
export default function AgentActivity({onCommitted}:{onCommitted:()=>void}){
  const [items,setItems]=useState<ApprovalRequest[]>([]); const [selected,setSelected]=useState<ApprovalRequest|null>(null);
  const [action,setAction]=useState<'approve'|'reject'|'revise'|null>(null); const [reason,setReason]=useState(''); const [error,setError]=useState(''); const [receipt,setReceipt]=useState<OperationReceipt|null>(null); const [undo,setUndo]=useState<OperationPreview|null>(null);
  const load=async()=>{try{const next=await commands.listApprovals();setItems(next);if(selected)setSelected(next.find(v=>v.id===selected.id)??null)}catch(e){setError((e as RowvaError).message??'Unable to load approvals')}};
  useEffect(()=>{void load()},[]);
  const approve=async()=>{if(!selected)return;try{const next=await commands.approve(selected.id,selected.proposal_fingerprint,reason||undefined);setReceipt(next);setAction(null);onCommitted();await load()}catch(e){setError((e as RowvaError).message??'Approval did not execute');setAction(null);await load()}};
  const reject=async()=>{if(!selected)return;try{await commands.reject(selected.id,reason||undefined);setAction(null);await load()}catch(e){setError((e as RowvaError).message??'Rejection failed')}};
  const revise=async()=>{if(!selected)return;try{const replacements=Object.fromEntries(selected.operation.changes.filter(c=>c.field_id).map(c=>[c.field_id as string,c.after]));await commands.revise(selected.id,replacements,reason||'Human revision');setAction(null);await load()}catch(e){setError((e as RowvaError).message??'Revision failed')}};
  const previewUndo=async()=>{if(!receipt)return;try{setUndo(await commands.previewUndo(receipt.operation_id,'Restore the values changed by this operation'))}catch(e){setError((e as RowvaError).message??'Undo is not safe')}};
  const commitUndo=async()=>{if(!undo)return;try{setReceipt(await commands.commitUndo(undo.operation_id,undo.preview_fingerprint));setUndo(null);onCommitted();await load()}catch(e){setError((e as RowvaError).message??'Undo conflicted')}};
  return <div className="grid grid-cols-[320px_1fr] gap-5">
    <aside className="border border-zinc-800 rounded bg-zinc-900 p-3"><div className="flex justify-between mb-3"><h2 className="font-semibold">Approval inbox</h2><button onClick={()=>void load()} className="text-emerald-400">Refresh</button></div>{items.length===0&&<p className="text-zinc-500 text-sm">No agent proposals yet.</p>}{items.map(item=><button key={item.id} onClick={()=>{setSelected(item);setReceipt(null);setError('')}} className="block w-full text-left border-b border-zinc-800 p-3 hover:bg-zinc-800"><div className="text-sm">{item.operation.kind.replaceAll('_',' ')}</div><div className="text-xs text-zinc-400">{item.requested_by.display_name} · {item.status}</div><div className="text-xs text-zinc-500 truncate">{item.operation.reason||'No reason supplied'}</div></button>)}</aside>
    <section className="border border-zinc-800 rounded bg-zinc-900 p-6">{!selected?<p className="text-zinc-500">Select a proposal to inspect its impact.</p>:<><div className="flex justify-between"><div><h2 className="text-2xl capitalize">{selected.operation.kind.replaceAll('_',' ')}</h2><p className="text-zinc-400">Requested by {selected.requested_by.display_name}{selected.requested_by.actor_version?` v${selected.requested_by.actor_version}`:''}</p></div><span className="h-fit rounded bg-amber-950 text-amber-300 px-3 py-1">{selected.status}</span></div><p className="mt-4">{selected.operation.reason||'No reason supplied.'}</p><div className="text-xs text-zinc-500 mt-2">Created {new Date(selected.requested_at).toLocaleString()} · expires {new Date(selected.expires_at).toLocaleString()}</div><div className="mt-5"><h3 className="font-semibold mb-2">Proposed changes</h3>{selected.operation.changes.map((c,i)=><div key={i} className="rounded bg-zinc-950 border border-zinc-800 p-3 mb-2"><div className="text-xs text-zinc-500">Field {c.field_id}</div><div className="break-words"><span className="text-red-300">{value(c.before)}</span> → <span className="text-emerald-300">{value(c.after)}</span></div></div>)}</div><div className="text-sm text-zinc-400">Policy: {selected.policy_reason_codes.join(', ')}</div>{selected.status==='pending'&&<div className="flex gap-2 mt-6"><button onClick={()=>setAction('approve')} className="bg-emerald-600 px-4 py-2 rounded">Approve and execute</button><button onClick={()=>setAction('revise')} className="bg-zinc-700 px-4 py-2 rounded">Edit proposal</button><button onClick={()=>setAction('reject')} className="bg-red-900 px-4 py-2 rounded">Reject</button></div>}</>}{error&&<div className="mt-4 border border-red-800 bg-red-950 p-3">Nothing was changed. {error}</div>}{receipt&&<div className="mt-4 border border-emerald-800 bg-emerald-950 p-4"><b>Durable receipt</b><div className="text-xs mt-1">{receipt.operation_id} · {receipt.status}</div>{receipt.status==='committed'&&<button onClick={()=>void previewUndo()} className="mt-3 underline">Preview undo</button>}</div>}{undo&&<div className="mt-4 border border-amber-700 p-4"><b>Undo preview</b>{undo.changes.map((c,i)=><div key={i}>{value(c.before)} → {value(c.after)}</div>)}<button onClick={()=>void commitUndo()} className="mt-3 bg-amber-600 px-3 py-2 rounded">Commit undo</button></div>}</section>
    {action&&<div className="fixed inset-0 bg-black/70 flex items-center justify-center"><div className="w-[480px] bg-zinc-900 border border-zinc-700 rounded p-6"><h3 className="text-xl capitalize">{action} proposal</h3><p className="text-sm text-zinc-400 my-3">{action==='revise'?'Revision creates a new proposal and preserves this one.':'This decision is durable and bound to the displayed fingerprint.'}</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Decision or revision reason (optional)" className="w-full h-28 bg-zinc-950 border border-zinc-700 p-3"/><div className="flex justify-end gap-2 mt-4"><button onClick={()=>setAction(null)}>Cancel</button><button onClick={()=>void(action==='approve'?approve():action==='reject'?reject():revise())} className="bg-emerald-600 px-4 py-2 rounded">Continue</button></div></div></div>}
  </div>
}
